import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({
    data: [
      {
        id: 1,
        title: 'Alimentação',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaUtensils',
      },
      {
        id: 2,
        title: 'Estudo',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaBook',
      },
      {
        id: 3,
        title: 'Higiene',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaShower',
      },
      {
        id: 4,
        title: 'Lazer',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaFilm',
      },
      {
        id: 5,
        title: 'Médico',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaPills',
      },
      {
        id: 6,
        title: 'Moradia',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaHouse',
      },
      {
        id: 7,
        title: 'Transporte',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaBusSimple',
      },
      {
        id: 8,
        title: 'Profissional',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaComputer',
      },
      {
        id: 9,
        title: 'Outros',
        description: 'description...',
        dueDate: '01/08/2023',
        categoryId: 1,
        typeExpenseId: 1,
        userId: 1,
        createdAt: '2023-08-30 22:00:00',
        icon: 'FaEllipsis',
      },
    ],
  })
}
